# Generated by Django 4.2.6 on 2023-11-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=5)),
                ('temperature', models.CharField(max_length=3)),
                ('area', models.CharField(max_length=5)),
                ('humidity', models.CharField(max_length=2)),
                ('chances', models.CharField(max_length=2)),
                ('date', models.DateField()),
            ],
        ),
    ]
