# Generated by Django 4.2.6 on 2023-11-08 13:37

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=7, validators=[app.models.val_climate])),
                ('temperature', models.IntegerField(max_length=4)),
                ('area', models.IntegerField(max_length=5, validators=[app.models.val_range])),
                ('humidity', models.IntegerField(max_length=4)),
                ('chances', models.IntegerField(max_length=2)),
                ('date', models.DateField()),
            ],
        ),
    ]
